chore: add httaccess
fix: fixe macos dependencies

fix: add test log

fix: fixe unformated

fix: fixe fmt error

fix: fixe update json

fix: fixe package version

fix: fixe bugs

fix: fixe

fix: fixe windows error

fix: fixe macos if

fix: separate steps

fix: fixe syntax error

fix: fixe windows generate json

fix: fixe attestations path and create update json

fix: fixe type module and add end release

fix: fixe

fix: fixe syntax error in end-release

fix: remove test for speed

fix: re add latest json creation

fix: fixe action yml

fix: fixe typo in workflow and add node

fix: fixe end release

fix: add sig cache

fix: change script to cat in bash

fix: fixe

fix: cache and release upload

fix: fixe sig paths

fix: fixe tauri prod

fix: fixe sign paths

fix: fixe extract signature

fix: fixe sign macos and widnows path

fix: fixe release id var

ci: change to future workflows

fix: fixe pushe

fix: fixe comments in CI

fix: change release step name in CI

fix: change workflow name

fix: fixe syntax error

fix: move ifs

fix: fixe identation

fix: fixe identation

fix: fixe identation in linux

fix: fixe outputs

fix: fixe linux echo

fix: fixe reusable workflow call

fix: fixe linux job output

fix: fixe workflow calls

fix: fixe macos

diff --git a/.github/workflows/PublishLinuxOS.yml b/.github/workflows/PublishLinuxOS.yml
--- a/.github/workflows/PublishLinuxOS.yml
+++ b/.github/workflows/PublishLinuxOS.yml
@@ -1,4 +1,4 @@
-name: Linux Build and Release
+name: LinuxBuildAndRelease
 
 on:
   workflow_call:
@@ -9,29 +9,28 @@ on:
       package_version:
         required: true
         type: string
+    outputs:
+      linux_x86_64_sig:
+        description: "Signature for Linux x86_64 build"
+        value: ${{ jobs.linuxBuilding.outputs.linux_x86_64_sig }}
 
 jobs:
-  build:
-    name: BuildLinux
+  linuxBuilding:
     if: "github.event.repository.fork == false"
+    name: BuildLinux
     permissions:
       contents: write
       id-token: write
+      security-events: write
+      attestations: write
+    outputs:
+      linux_x86_64_sig: ${{ steps.extract-signatures.outputs.linux_x86_64_sig }}
     strategy:
       fail-fast: false
       matrix:
         include:
           - target: x86_64-unknown-linux-gnu
             platform: linux/amd64
-            symbol: 🐧
-          - target: i686-unknown-linux-gnu
-            platform: linux/amd64
-            symbol: 🐧
-          - target: aarch64-unknown-linux-gnu
-            platform: linux/arm64
-            symbol: 🐧
-          - target: armv7-unknown-linux-gnueabihf
-            platform: linux/arm/v7
             symbol: 🐧
 
     runs-on: ubuntu-latest
@@ -65,7 +64,7 @@ jobs:
             libjavascriptcoregtk-4.1-dev \
             pkg-config
 
-     - name: 🦀 Install rust stable
+      - name: 🦀 Install rust stable
         uses: dtolnay/rust-toolchain@stable
         with:
           targets: wasm32-unknown-unknown
@@ -101,4 +100,49 @@ jobs:
         with:
           releaseId: ${{ inputs.release_id }}
           tauriScript: cargo --locked auditable tauri
-          args: '--target ${{ matrix.args }}'
+          args: '--target ${{ matrix.target }}'
+
+      - name: Extract Signatures and Set Outputs
+        id: extract-signatures
+        run: |
+          package_version="${{ inputs.package_version }}"
+
+          read_signature() {
+            local file="$1"
+            if [[ ! -f "$file" ]]; then
+              echo "Error: File $file not found" >&2
+              exit 1
+            fi
+            tr -d '\n' < "$file" | xargs
+          }
+
+          linux_x86_64_sig=$(read_signature "src-tauri/target/${{ matrix.target }}/release/bundle/appimage/codefend-panel_${package_version}_amd64.AppImage.sig")
+
+          echo "Signatures extracted successfully."
+          echo "linux_x86_64_sig=$linux_x86_64_sig" >> $GITHUB_OUTPUT
+
+      - name: 🛡️ Attest build provenance (publish release only)
+        uses: actions/attest-build-provenance@7668571508540a607bdfd90a87a560489fe372eb # v2.1.0
+        env:
+          CARGO_HOME: /home/runner/.cargo
+          CARGO_INCREMENTAL: 0
+          CARGO_TERM_COLOR: always
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          subject-path: src-tauri/target/${{ matrix.target }}/release/bundle/*
+          push-to-registry: false
+          show-summary: true
+          github-token: ${{ env.GITHUB_TOKEN }}
+  
+      - name: 📜 Create SBOM
+        uses: anchore/sbom-action@55dc4ee22412511ee8c3142cbea40418e6cec693 # v0
+        with:
+          format: "spdx-json"
+          output-file: "sbom.spdx.json"
+          artifact-name: "linux_${{ matrix.target }}.sbom.spdx.json"
+  
+      - name: 🛡️ Attest SBOM
+        uses: actions/attest-sbom@v2
+        with:
+          subject-path: 'src-tauri/target/${{ matrix.target }}/release/codefend-panel'
+          sbom-path: "sbom.spdx.json"
